### PR TITLE
Removed call to System.gc when terminating a thread.

### LINKED ISSUE #128: Massive performance hit
We are currently running the OpenNTF API in the version released as the Runtime Essentials back in December (version 1.0.0.201312231409). When enabling the latest version of the API (1.5.0.201409241744) we are experiencing a massive performance hit for our XPage applications. In production where our servers perform smoothly, enabling the new version leads to the server not keeping up with incoming users in the morning rendering it unresponsive (most of the users are configured to open a specific application).
A simple load test we perform verifies the behavior also for our test servers. Here the server takes roughly twice the amount of time to deliver the same amount of requests to the application compared to the older version.
The load test simply starts a new thread every 100ms which reads the same URL (entry Page for our main application). For a fixed amount of threads we watch the time it takes to complete those threads. Using the RC2 version of the API the load test roughly runs twice as long.
We can toggle the used version and the server speeds up or slows respectively. We've tested it against different applications and different XPages, getting the same result every time. 
We don't use the plugin yet. We are just in the stage of getting it out so we can utilize it in the future.
Currently we are running Domino 9.0.1FP1 on Windows 2003/2008/64bit servers. We have installed the ExtensionLibrary version 9.0.1.v00_08_20140729-0805 as well as OpenNTF Essentials Runtime modules as of version 901v2.

### PR DESCRIPTION
**Pull request by mariusj**
This call kills performance of the server (up to 10x slower throughput).
Bellow is sample report from XpagesToolbox monitoring.

Type | Count | Total time | Max time | Avg time | Min time | Specific time
-----|-------|------------|----------|----------|----------|--------------
ODA disabled |  500 | 671 | 80 | 1 | 0 | 140
develop | 500 | 21461 | 100 | 43 | 20 | 20259
with fix | 500 | 761 | 60 | 2 | 0 | 120	

I've opened an empty XPage using 100 threads. First result is with ODA completly disabled. Second is with current develop branch, third is with System.gc() removed.

Maybe it will fix #128.

### CODE REVIEW

**Comment by the-ntf** [comment]
The System.gc() there in order to recover the WeakReferences to the
reference queue of lotus.domino handles that need to be auto-recycled.
However, in the try block, there is a forced recycle of all outstanding
Sessions, which itself should recycle any outstanding lotus objects because
they are all parented to Sessions.

Therefore I think this is a good change, and I've tested it with success,
so I'm committing it to my branch. Not through the pull request, though,
because I have other changes in my Factory that need to stay intact. :)

Well-spotted!

**Comment by mariusj** [comment]
The System.gc call was not removed from 2.0.0 release so this release is also affected by this huge performance slowdown.

**Comment by jesse-gallagher** [comment]
The change hasn't made it up to the GitHub repo yet, so it wasn't around for 2.0.0 packaging. Presumably, it'll make it into a release shortly.

**Comment by jesse-gallagher** [comment]
Looks like this was indeed implemented with a wave of Nathan's changes a couple weeks ago, so I'll close this pull request.

**Comment by MarkusLanger** [comment]
When will there be a new version on the OpenNTF project?

**Pull request closed without merging**
